name: "Bug report"
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Steps to reproduce
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g. 0.1.1
  - type: textarea
    id: logs
    attributes:
      label: Logs
