name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install
        run: |
          python -m pip install -U pip
          # api + أدوات الاختبار والبناء
          pip install -e ".[api]" pytest build twine bandit
      - name: Unit tests
        run: pytest -q
      - name: Self-check smoke
        run: bash scripts/self_check.sh
      - name: Build dist
        run: python -m build
      - name: Twine check
        run: python -m twine check dist/*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.python-version }}
          path: dist/*
