name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Build
        run: |
          python -m pip install -U pip build
          python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Make release bundle (zip)
        run: |
          bash scripts/make_release.sh
      - name: Attach assets to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
            release/*.zip
            release/*.sha256
          generate_release_notes: true
